name: Build Chain Specs

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ kories ]
  pull_request:
    branches: [ kories ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-specs:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt update && sudo apt upgrade && sudo apt install -y git clang curl libssl-dev llvm libudev-dev

      - name: Install Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Build
        run: |
          cargo build

      - name: Build Specs
        run: |
          ./target/debug/kories-node build-spec --dev --disable-default-bootnode > dev-spec.json &&
          ./target/debug/kories-node build-spec --dev --disable-default-bootnode --raw > dev-spec-raw.json &&
          ./target/debug/kories-node build-spec --disable-default-bootnode > spec.json &&
          ./target/debug/kories-node build-spec --disable-default-bootnode --raw > spec-raw.json
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dev-spec.json
            dev-spec-raw.json
            spec.json
            spec-raw.json
